name: restaurants_test
description: A new Flutter project.



version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  mask_text_input_formatter: ^2.4.0
  intl: ^0.17.0
  flutter_svg: ^1.1.2
  flutter_styled_toast: ^2.1.3
  dio: ^4.0.6
  shared_preferences: ^2.0.15
  flutter_bloc: ^8.0.1
  freezed: ^2.1.0+1
  freezed_annotation: ^2.1.0
  json_annotation: ^4.6.0
  auto_route: ^4.2.1
  easy_localization: ^3.0.1
  get_it: ^7.2.0
  json_serializable: ^6.3.1
  cupertino_icons: ^1.0.2
  injectable: ^1.5.3
  cached_network_image: ^3.2.1
  google_maps_flutter: ^2.2.0
  geolocator: ^9.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  injectable_generator: ^1.5.4
  build_runner: ^2.2.0
  auto_route_generator: ^4.2.1
  dart_code_metrics: ^4.17.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
  fonts:
    - family: Manrope
      fonts:
        - asset: assets/fonts/Manrope.ttf
  